__default__:
  jobname: "{rule}.{wildcards}"
  nodes: 1
  ntaskspernode: 1
  cpuspertask: 1
  mempercpu: "1gb"
  time: "1:00:00"
  account: "esnitkin1"
  partition: "standard"
  mailuser: "UNIQNAME@umich.edu"
  mailtype: "BEGIN,END,FAIL"
  output: "logfiles/%x-%j.out"

# modify config for certain rules
plot_histogram:
  time: "10:00"

